# Generated by Django 5.0.4 on 2024-04-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='author',
            new_name='created_by',
        ),
    ]
