# Generated by Django 4.1.13 on 2024-05-07 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('paper_file', models.FileField(upload_to='PreviousYearPapers/%Y/')),
            ],
        ),
        migrations.RenameModel(
            old_name='PDFNotes',
            new_name='PDFNote',
        ),
    ]
