# Generated by Django 4.1.13 on 2024-05-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='pdfnote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pdfnote',
            name='title',
        ),
    ]
