# Generated by Django 4.1.13 on 2024-05-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_assignment_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper_file',
            new_name='pdf_file',
        ),
    ]
