# Generated by Django 4.1.13 on 2024-05-07 14:27

from django.db import migrations, models
import resources.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_paper_rename_pdfnotes_pdfnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_file',
            field=models.FileField(upload_to=resources.models.get_upload_path),
        ),
    ]
